/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : CBHeroCharacter.sm
 */


#import "statemap.h"

// Forward declarations.
@class HeroMap;
@class HeroMap_Standing;
@class HeroMap_Running;
@class HeroMap_Jumping;
@class HeroMap_Falling;
@class HeroMap_Climbing;
@class HeroMap_Dying;
@class HeroMap_Default;
@class CBHeroCharacterState;
@class CBHeroCharacterContext;
@class HeroCharacter;

@interface CBHeroCharacterState : SMCState
{
}
- (void)Entry:(CBHeroCharacterContext*)context;
- (void)Exit:(CBHeroCharacterContext*)context;

- (void)toClimb:(CBHeroCharacterContext*)context;
- (void)toDie:(CBHeroCharacterContext*)context;
- (void)toFall:(CBHeroCharacterContext*)context;
- (void)toJump:(CBHeroCharacterContext*)context;
- (void)toRun:(CBHeroCharacterContext*)context;
- (void)toStand:(CBHeroCharacterContext*)context;
- (void)update:(CBHeroCharacterContext*)context :(NSTimeInterval)delta;

- (void)Default:(CBHeroCharacterContext*)context;
@end

@interface HeroMap : NSObject
{
}
+ (HeroMap_Standing*)Standing;
+ (HeroMap_Running*)Running;
+ (HeroMap_Jumping*)Jumping;
+ (HeroMap_Falling*)Falling;
+ (HeroMap_Climbing*)Climbing;
+ (HeroMap_Dying*)Dying;
@end

@interface HeroMap_Default : CBHeroCharacterState
{
}
- (void)toStand:(CBHeroCharacterContext*)context;
- (void)toRun:(CBHeroCharacterContext*)context;
- (void)toJump:(CBHeroCharacterContext*)context;
- (void)toFall:(CBHeroCharacterContext*)context;
- (void)toClimb:(CBHeroCharacterContext*)context;
- (void)toDie:(CBHeroCharacterContext*)context;
- (void)update:(CBHeroCharacterContext*)context :(NSTimeInterval)delta;
@end

@interface HeroMap_Standing : HeroMap_Default
{
}
 -(void)Entry:(CBHeroCharacterContext*)context;
- (void)toJump:(CBHeroCharacterContext*)context;
- (void)toRun:(CBHeroCharacterContext*)context;
@end

@interface HeroMap_Running : HeroMap_Default
{
}
 -(void)Entry:(CBHeroCharacterContext*)context;
- (void)toFall:(CBHeroCharacterContext*)context;
- (void)toJump:(CBHeroCharacterContext*)context;
- (void)toStand:(CBHeroCharacterContext*)context;
- (void)update:(CBHeroCharacterContext*)context :(NSTimeInterval)delta;
@end

@interface HeroMap_Jumping : HeroMap_Default
{
}
 -(void)Entry:(CBHeroCharacterContext*)context;
- (void)toClimb:(CBHeroCharacterContext*)context;
- (void)toFall:(CBHeroCharacterContext*)context;
- (void)update:(CBHeroCharacterContext*)context :(NSTimeInterval)delta;
@end

@interface HeroMap_Falling : HeroMap_Default
{
}
 -(void)Entry:(CBHeroCharacterContext*)context;
- (void)toClimb:(CBHeroCharacterContext*)context;
- (void)toStand:(CBHeroCharacterContext*)context;
- (void)update:(CBHeroCharacterContext*)context :(NSTimeInterval)delta;
@end

@interface HeroMap_Climbing : HeroMap_Default
{
}
 -(void)Entry:(CBHeroCharacterContext*)context;
- (void)toFall:(CBHeroCharacterContext*)context;
- (void)toJump:(CBHeroCharacterContext*)context;
- (void)toStand:(CBHeroCharacterContext*)context;
- (void)update:(CBHeroCharacterContext*)context :(NSTimeInterval)delta;
@end

@interface HeroMap_Dying : HeroMap_Default
{
}
 -(void)Entry:(CBHeroCharacterContext*)context;
@end

@interface CBHeroCharacterContext : SMCFSMContext
{
    __weak HeroCharacter *_owner;
}
- (id)initWithOwner:(HeroCharacter*)owner;
- (id)initWithOwner:(HeroCharacter*)owner state:(SMCState*)aState;
- (HeroCharacter*)owner;
- (CBHeroCharacterState*)state;

- (void)enterStartState;

- (void)toClimb;
- (void)toDie;
- (void)toFall;
- (void)toJump;
- (void)toRun;
- (void)toStand;
- (void)update:(NSTimeInterval)delta;
@end


/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
